version: '3'
services:

  mariadb:
      image: mariadb
      environment:
          - MYSQL_ROOT_PASSWORD=password

  postgres:
      image: postgres
      environment:
          - POSTGRES_PASSWORD=password

  r:
    image: rocker/tidyverse
    volumes:
      - .:/data
    working_dir: /data
    depends_on:
      - postgres
      - mariadb



